SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS room_availabilities;
DROP TABLE IF EXISTS room_images;
DROP TABLE IF EXISTS room_types;
DROP TABLE IF EXISTS hotel_facilities;
DROP TABLE IF EXISTS hotel_images;
DROP TABLE IF EXISTS hotels;
SET FOREIGN_KEY_CHECKS = 1;
