-- 008_add_hotel_location_fields.up.sql

ALTER TABLE hotels ADD COLUMN IF NOT EXISTS type VARCHAR(50) DEFAULT 'hotel';
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS base_price DECIMAL(15,2) DEFAULT 0;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS room_count INTEGER DEFAULT 0;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 8);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS longitude DECIMAL(11, 8);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active';

CREATE INDEX IF NOT EXISTS idx_hotels_type ON hotels(type);
CREATE INDEX IF NOT EXISTS idx_hotels_status ON hotels(status);
