SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS passengers;
DROP TABLE IF EXISTS flight_bookings;
DROP TABLE IF EXISTS hotel_vouchers;
DROP TABLE IF EXISTS e_tickets;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS bookings;
SET FOREIGN_KEY_CHECKS = 1;
